PRGRM_HDR: Attempted to fix "void" errors
ERROR:  105: error: invalid use of void expression
Type cast "segmentArray" member of 'dynamic' structs possibly assigned.  Hopefully this is enough to resolve the error.  While we're at it, hopefully it takes care of the "warning: dereferencing ‘void ’ pointer" warnings as well.

WRITTEN OFFLINE.  REQUIRES TESTING!

-H